// Generated by gencpp from file scki2725_hw2/TimeCheck.msg
// DO NOT EDIT!


#ifndef SCKI2725_HW2_MESSAGE_TIMECHECK_H
#define SCKI2725_HW2_MESSAGE_TIMECHECK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace scki2725_hw2
{
template <class ContainerAllocator>
struct TimeCheck_
{
  typedef TimeCheck_<ContainerAllocator> Type;

  TimeCheck_()
    : header()
    , checking(0.0)  {
    }
  TimeCheck_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , checking(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _checking_type;
  _checking_type checking;





  typedef boost::shared_ptr< ::scki2725_hw2::TimeCheck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scki2725_hw2::TimeCheck_<ContainerAllocator> const> ConstPtr;

}; // struct TimeCheck_

typedef ::scki2725_hw2::TimeCheck_<std::allocator<void> > TimeCheck;

typedef boost::shared_ptr< ::scki2725_hw2::TimeCheck > TimeCheckPtr;
typedef boost::shared_ptr< ::scki2725_hw2::TimeCheck const> TimeCheckConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scki2725_hw2::TimeCheck_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scki2725_hw2::TimeCheck_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scki2725_hw2::TimeCheck_<ContainerAllocator1> & lhs, const ::scki2725_hw2::TimeCheck_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.checking == rhs.checking;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scki2725_hw2::TimeCheck_<ContainerAllocator1> & lhs, const ::scki2725_hw2::TimeCheck_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scki2725_hw2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scki2725_hw2::TimeCheck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scki2725_hw2::TimeCheck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scki2725_hw2::TimeCheck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scki2725_hw2::TimeCheck_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scki2725_hw2::TimeCheck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scki2725_hw2::TimeCheck_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scki2725_hw2::TimeCheck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a43739a327e2a965e0fd1f1de9acbb9";
  }

  static const char* value(const ::scki2725_hw2::TimeCheck_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a43739a327e2a96ULL;
  static const uint64_t static_value2 = 0x5e0fd1f1de9acbb9ULL;
};

template<class ContainerAllocator>
struct DataType< ::scki2725_hw2::TimeCheck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scki2725_hw2/TimeCheck";
  }

  static const char* value(const ::scki2725_hw2::TimeCheck_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scki2725_hw2::TimeCheck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 checking\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::scki2725_hw2::TimeCheck_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scki2725_hw2::TimeCheck_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.checking);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeCheck_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scki2725_hw2::TimeCheck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scki2725_hw2::TimeCheck_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "checking: ";
    Printer<double>::stream(s, indent + "  ", v.checking);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCKI2725_HW2_MESSAGE_TIMECHECK_H
