// Generated by gencpp from file scki2725_hw2/TimerResponse.msg
// DO NOT EDIT!


#ifndef SCKI2725_HW2_MESSAGE_TIMERRESPONSE_H
#define SCKI2725_HW2_MESSAGE_TIMERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scki2725_hw2
{
template <class ContainerAllocator>
struct TimerResponse_
{
  typedef TimerResponse_<ContainerAllocator> Type;

  TimerResponse_()
    : clock(0.0)
    , stamp()  {
    }
  TimerResponse_(const ContainerAllocator& _alloc)
    : clock(0.0)
    , stamp()  {
  (void)_alloc;
    }



   typedef double _clock_type;
  _clock_type clock;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::scki2725_hw2::TimerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scki2725_hw2::TimerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TimerResponse_

typedef ::scki2725_hw2::TimerResponse_<std::allocator<void> > TimerResponse;

typedef boost::shared_ptr< ::scki2725_hw2::TimerResponse > TimerResponsePtr;
typedef boost::shared_ptr< ::scki2725_hw2::TimerResponse const> TimerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scki2725_hw2::TimerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scki2725_hw2::TimerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scki2725_hw2::TimerResponse_<ContainerAllocator1> & lhs, const ::scki2725_hw2::TimerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.clock == rhs.clock &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scki2725_hw2::TimerResponse_<ContainerAllocator1> & lhs, const ::scki2725_hw2::TimerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scki2725_hw2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scki2725_hw2::TimerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scki2725_hw2::TimerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scki2725_hw2::TimerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scki2725_hw2::TimerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scki2725_hw2::TimerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scki2725_hw2::TimerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scki2725_hw2::TimerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d593ef9452dfc837176d09f400fd3fd3";
  }

  static const char* value(const ::scki2725_hw2::TimerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd593ef9452dfc837ULL;
  static const uint64_t static_value2 = 0x176d09f400fd3fd3ULL;
};

template<class ContainerAllocator>
struct DataType< ::scki2725_hw2::TimerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scki2725_hw2/TimerResponse";
  }

  static const char* value(const ::scki2725_hw2::TimerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scki2725_hw2::TimerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 clock\n"
"time stamp\n"
;
  }

  static const char* value(const ::scki2725_hw2::TimerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scki2725_hw2::TimerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clock);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scki2725_hw2::TimerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scki2725_hw2::TimerResponse_<ContainerAllocator>& v)
  {
    s << indent << "clock: ";
    Printer<double>::stream(s, indent + "  ", v.clock);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCKI2725_HW2_MESSAGE_TIMERRESPONSE_H
